<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <!-- Identificación del proyecto -->
    <groupId>ISO2</groupId>
    <artifactId>labB3</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>labB3 (Proyecto Maven Padre)</name>
    <description>Proyecto multi-módulo de ejemplo para cliente/servidor</description>

    <modules>
        <module>it1</module>
    </modules>

    <dependencies>
        <!-- Dependencia de JUnit 5 -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>5.10.2</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
